version: '3.1'

services:

    spring_db:
        image: mysql:8.0.27
        restart: always
        environment:
          - MYSQL_DATABASE=prods
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - mysql_db:/var/lib/mysql
      
      
    mikrostoritev:
        build: .
        restart: always
        ports:
            - 8080:8080
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://spring_db:3306/prods
        depends_on:
            - spring_db
            
            
volumes:
    mysql_db:             
