version: '3.1'

services:

    spring_db:
        image: mysql:8.0.26
        restart: always
        environment:
          - MYSQL_DATABASE=voteitdb
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - mysql_db:/var/lib/mysql
      
    backend:
        build: .
        restart: always
        ports:
            - 8080:8888
        environment:
            - SPRING_PROFILES_ACTIVE=mysql
            - SPRING_DATASOURCE_URL=jdbc:mysql://spring_db:3306/voteitdb

volumes:
    mysql_db: